### ISSUE TITLE
vod

### ISSUE THREAD

**Issue by altrax457** [fairy-root/mac-to-m3u#2]
you can add the ability to download vod from the list

**Comment by fairy-root** [comment]
Yes, I am aware of that, yet since it will be mixed with the channels, I discarded the idea.
I'll make another script that contains channels, vod, and series as well.

**Comment by altrax457** [comment]
Is it possible to separate this by categories?
I tried to add vod download from myself however it didn't work I only added channel download by country prefix

**Comment by fairy-root** [comment]
**I can add a tool to extract or delete channels of any group name
I.E.** 
- _Extract channels of group name that has any occurrence of_ **"France"** _to a new m3u file_
- _Delete any channels of group name that has any occurrence of_ **"France"** _from the original m3u file_

**However this feature will be in a separate python file, and not embedded in the original code.**
