### ISSUE TITLE
Does not collect

### ISSUE THREAD

**Issue by Pe0xonN** [fairy-root/mac-to-m3u#3]
Does not collect all channels

**Comment by fairy-root** [comment]
Explain more

**Comment by Pe0xonN** [comment]
I enter the address and mac and it does not collect all channels

**Comment by Pe0xonN** [comment]
E.g. 300 out of 1000 channels

**Comment by Pe0xonN** [comment]
And I don't have the ones I want and they are on the list

**Comment by Pe0xonN** [comment]
@fairy-root You are

**Comment by fairy-root** [comment]
**_It did not happen on my end though I tested on lists of over 26k_**

**Text me here, and if the issue is in the script, I'll update it**
- Telegram: ```https://t.me/FairyRoot```

**Comment by Pe0xonN** [comment]
Fixed

**Comment by Pe0xonN** [comment]
Already fixed
